In [1]:
import pandas as pd
import numpy as np
sales = pd.read_csv(r"D:\amazon_agent_ai\data\sales_data.csv")
ads = pd.read_csv(r"D:\amazon_agent_ai\data\keyword_ad_data.csv")

In [3]:
sales.head()

,asin,product_title,category,sub_category,date,units_sold,selling_price,unit_cost,fba_fees,revenue,profit_margin_pct,bsr_rank,stock_level
0,B09L4ZTM2V,NaturaCare Natural Pimple Face Gel-50 G || Nat...,Face gel,Pimple Face Gel,2026-01-01,1,404.15,0.0,3.88,404.15,NaN,0,0
1,B0BKLQHQ8B,NaturaCare Black Spot Cream-30g || A revolutio...,Face care,Face Creams,2026-01-01,1,616.50,0.0,12.70,616.50,NaN,0,0
2,B0BKZW578S,NaturaCare Natural Red Sandal Shine & Glow Fac...,skin glow and tan,Face Pack,2026-01-01,1,404.15,0.0,9.70,404.15,NaN,0,0
3,B0BL43KX8L,NaturaCare Natural Coffee De-Tan Scrub-50g wit...,Face care,De-Tan Scrub,2026-01-01,1,404.15,0.0,6.47,404.15,NaN,0,0
4,B0BL73PT5W,NaturaCare Natural Anti-Acne Face Wash-100ml w...,Face Wash,Anti-Acne Face Wash,2026-01-01,1,404.15,0.0,8.62,404.15,NaN,0,0

In [4]:
ads.head()

,asin,keyword,match_type,date,impressions,clicks,cpc,ad_spend,attributed_sales,attributed_units,acos
0,07-IRQL-T5BS,complements,TARGETING_EXPRESSION_PREDEFINED,2026-01-01,15,2,16.25,32.50,0.0,0,0.0
1,09-NY8V-51DZ,close-match,TARGETING_EXPRESSION_PREDEFINED,2026-01-01,0,0,10.05,1.34,0.0,0,0.0
2,09-NY8V-51DZ,complements,TARGETING_EXPRESSION_PREDEFINED,2026-01-01,4,0,14.57,3.89,0.0,0,0.0
3,09-NY8V-51DZ,loose-match,TARGETING_EXPRESSION_PREDEFINED,2026-01-01,4,0,17.62,7.05,0.0,0,0.0
4,09-NY8V-51DZ,substitutes,TARGETING_EXPRESSION_PREDEFINED,2026-01-01,117,1,15.94,19.13,0.0,0,0.0

In [6]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   asin               1440 non-null   object
 1   product_title      1440 non-null   object
 2   category           1440 non-null   object
 3   sub_category       1434 non-null   object
 4   date               1440 non-null   object
 5   units_sold         1440 non-null   int64
 6   selling_price      1440 non-null   float64
 7   unit_cost          1440 non-null   float64
 8   fba_fees           1440 non-null   float64
 9   revenue            1440 non-null   float64
 10  profit_margin_pct  404 non-null    float64
 11  bsr_rank           1440 non-null   int64
 12  stock_level        1440 non-null   int64
dtypes: float64(5), int64(3), object(5)
memory usage: 146.4+ KB

In [7]:
ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7471 entries, 0 to 7470
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   asin              7471 non-null   object
 1   keyword           7471 non-null   object
 2   match_type        7471 non-null   object
 3   date              7471 non-null   object
 4   impressions       7471 non-null   int64
 5   clicks            7471 non-null   int64
 6   cpc               7471 non-null   float64
 7   ad_spend          7471 non-null   float64
 8   attributed_sales  7471 non-null   float64
 9   attributed_units  7471 non-null   int64
 10  acos              7471 non-null   float64
dtypes: float64(4), int64(3), object(4)
memory usage: 642.2+ KB

In [8]:
sales.describe()

,units_sold,selling_price,unit_cost,fba_fees,revenue,profit_margin_pct,bsr_rank,stock_level
count,1440.000000,1440.000000,1440.000000,1440.000000,1440.000000,404.000000,1440.0,1440.0
mean,8.753472,551.215340,1.522222,19.552333,4928.829326,97.643342,0.0,0.0
std,15.958848,253.795301,10.100788,27.669689,10768.440289,3.647977,0.0,0.0
min,1.000000,197.280000,0.000000,0.000000,197.280000,81.130000,0.0,0.0
25%,1.000000,404.150000,0.000000,7.270000,479.500000,95.065000,0.0,0.0
50%,2.000000,529.960000,0.000000,13.340000,1068.600000,100.000000,0.0,0.0
75%,7.000000,615.130000,0.000000,22.190000,3493.500000,100.000000,0.0,0.0
max,140.000000,1902.930000,68.500000,323.320000,80247.750000,100.000000,0.0,0.0

In [ ]:
ads.describe()

,impressions,clicks,cpc,ad_spend,attributed_sales,attributed_units,acos
count,7471.000000,7471.000000,7471.000000,7471.000000,7471.000000,7471.000000,7471.000000
mean,320.479186,7.617990,16.364076,102.433160,641.543610,1.067996,4.691621
std,1123.587773,24.864672,12.343953,347.801452,2976.044705,4.423732,16.774454
min,0.000000,0.000000,0.280000,0.010000,0.000000,0.000000,0.000000
25%,5.000000,1.000000,8.780000,7.720000,0.000000,0.000000,0.000000
50%,33.000000,2.000000,13.700000,21.830000,0.000000,0.000000,0.000000
75%,231.500000,5.000000,20.110000,64.235000,273.025000,1.000000,1.840000
max,28313.000000,333.000000,181.820000,5146.910000,50241.520000,62.000000,626.040000

In [10]:
sales.isnull().sum()

asin                    0
product_title           0
category                0
sub_category            6
date                    0
units_sold              0
selling_price           0
unit_cost               0
fba_fees                0
revenue                 0
profit_margin_pct    1036
bsr_rank                0
stock_level             0
dtype: int64

In [13]:
sales["sub_category"] = sales["sub_category"].fillna("Unknown")

In [14]:
sales["profit_margin_pct"] = (
    (sales["selling_price"] - sales["unit_cost"] - sales["fba_fees"])
    / sales["selling_price"]
) * 100

In [15]:
sales.isnull().sum()

asin                 0
product_title        0
category             0
sub_category         0
date                 0
units_sold           0
selling_price        0
unit_cost            0
fba_fees             0
revenue              0
profit_margin_pct    0
bsr_rank             0
stock_level          0
dtype: int64

In [11]:
ads.isnull().sum()

asin                0
keyword             0
match_type          0
date                0
impressions         0
clicks              0
cpc                 0
ad_spend            0
attributed_sales    0
attributed_units    0
acos                0
dtype: int64

In [12]:
sales["date"] = pd.to_datetime(sales["date"])
ads["date"] = pd.to_datetime(ads["date"])

In [ ]:
ads["acos"] = ads["ad_spend"] / ads["attributed_sales"]
ads["acos"] = ads["acos"].replace([np.inf, -np.inf], 0)
ads["acos"].fillna(0, inplace=True)

In [ ]:
ads["roas"] = ads["attributed_sales"] / ads["ad_spend"]
ads["roas"] = ads["roas"].replace([np.inf, -np.inf], 0)
ads["roas"].fillna(0, inplace=True)

In [21]:
sales["profit_per_unit"] = sales["selling_price"] - sales["unit_cost"] - sales["fba_fees"]

In [25]:
sales = sales.sort_values("date")
ads = ads.sort_values("date")

In [27]:
sales.to_csv("D:/amazon_agent_ai/data/sales_cleaned.csv", index=False)
ads.to_csv("D:/amazon_agent_ai/data/ads_cleaned.csv", index=False)